import type { Metadata } from "next";
import { Montserrat as Inter } from "next/font/google";
import "./globals.css";
import NavigationWithSidebar from "@/components/Navigation/Navigation";
import Footer from "@/components/Footer/Footer";
import Navigation from "@/components/Navigation/Navigation";

export const metadata: Metadata = {
    title: "CVSU Elits",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className="bg-gray-100">
                <div className="flex flex-col fixed w-full z-50">
                    <Navigation />
                </div>
                <main>
                    {children}
                    <Footer />
                </main>
            </body>
        </html>
    );
}
