"use client"
import "./globals.css";
import React, { Suspense } from 'react';
import Footer from '@/components/Footer/Footer';
import Navigation from '@/components/Navigation/Navigation';
import Loading from './loading';

const metadata = {
    title: "CVSU Elits",
    description: "Generated by create next app",
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {

    return (
        <>
            <html lang="en">
                <head>
                    <title>{metadata.title}</title>
                    <meta name="description" content={metadata.description} />
                </head>
                    <body className="bg-gray-100">
                        <Navigation />
                        <Suspense>
                                <main>{children}</main>
                        </Suspense>
                        <Footer />
                    </body>
            </html>
        </>
    );
};

export default RootLayout;
