import type { Metadata } from "next";
import { Montserrat as Inter } from "next/font/google";
import "./globals.css";
import NavigationWithSidebar from "@/components/Navigation/NavigationWithSidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "CVSU Elits",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <main>
                    <NavigationWithSidebar />
                    {children}
                </main>
            </body>
        </html>
    );
}
